Ab/registration
TankerHQ/spec pull request #9
Opened 2019-11-19 11:00 UTC by AlexandreBossard

2019-11-20 11:00 UTC, Marwyn42 submitted a review, later dismissed

2019-11-20 11:00 UTC, Marwyn42 commented on concepts.md
> +[Verification Method]: concepts.md#Verification-method "A verfication methond allow a user to retrieve its verification key"
A ver**i**fication metho**n**d allow**s**

2019-11-20 11:00 UTC, Marwyn42 commented on concepts.md
> + <dd>Allow a *user* to retrieve their verification key. Used during Device or User registration</dd>
Allow**s**

2019-11-20 11:00 UTC, Marwyn42 commented on concepts.md
> +[Verification Method]: concepts.md#Verification-method "A verfication methond allow a user to retrieve its verification key"
PLus other copy pastas of this line

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +*Tanker Core* creates another [Device Encryption Key Pair] and [Device Signature Key Pair] for the *virtual device*. But instead of storing them, it serialize them as an opaque token, the [Verificati
serialize**s**

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +Then, a second `device_creation` block is created with the *physical device*'s [Device Encryption Key Pair] and [Device Signature Key Pair]. This block is signed with the *virtual device*'s [Device S
Not exactly. In fact, the virtual device is used to sign a new ephemeral key pair, making a delegation signature from the virtual device to the new device

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +1. *Tanker Core* constructs the new *device*'s `device_creation` *block* with the *device id*, retrieved from the *Tanker server*, as the block author and signs it with the *virtual device*'s private
again, not exactly. There is an ephemeral key pair created at this point, signed by the virtual device

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +*User*s can use their [Verification Key] 'as is' when registering a new device. But, *Tanker Core* proposes easier way to handle the [Verification Key].
**an** easier way

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +When the *user* needs to [register a new device](#device-registration), they will provide their passphrase. *Tanker Core* will hash the passphrase before sending to the *Tanker server*. The *Tanker s
This sentences makes no sense

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +For the *application* to offer Email as a verification method, they need to send `HTTP` requests to the *Tanker server*. To allow that, the *application* administrator needs to register their domain
needs to register the**ir** domain origin of their requests to the *Tanker App*.

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +1. The *application* makes a request to the *Tanker server* with the provided email adress and some paylod for the email message
paylo**a**d

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +1. The *user* provides the [Verifcation Code] to the *application*
Verif**i**cation Code

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +If the *Tanker server* does not returns an error, it's mean the process has ended sucessfully and the *user* has now registered their provided email address as a [Verification Method].
it**'s** mean**s**

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +The process to [register a new device](#device-registration) with an email [Verification Method] is the same as describe above. The only difference is that at the end of the process the *Tankser serv
describe**d**

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +The process to [register a new device](#device-registration) with an email [Verification Method] is the same as describe above. The only difference is that at the end of the process the *Tankser serv
the *Tank**s**er server* return**s** the

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +The *user* authenticates against the OpenID Connect provider, which will allow the *application* to receive the *user* `ID Token`. Then, the *application* can provides this `ID Token` to *Tanker Core
and hash**ed** **the** it before storing it.

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +The process to [register a new device](#device-registration) with an `OIDC` [Verification Method] is the same as describe above. The only difference is that at the end of the process *Tanker server*
same as describe**d** above

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +The process to [register a new device](#device-registration) with an `OIDC` [Verification Method] is the same as describe above. The only difference is that at the end of the process *Tanker server*
*Tanker server* return**s**

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +This operation adds users to an existing user group. The group Id, [Group Encryption Key Pair] and the [Group Signature Key Pair] remain unchange at the end of the operation.
ID, not Id

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +This operation adds users to an existing user group. The group Id, [Group Encryption Key Pair] and the [Group Signature Key Pair] remain unchange at the end of the operation.
remain**s** unchange**d**

2019-11-20 11:00 UTC, Marwyn42 commented on protocol.md
> +This operation is similar to the previous one, the only difference is that it rotates the [Group Encryption Key Pair] and the [Group Signature Key Pair]. The group id remain unchanged.
group **ID** remain**s**

2019-11-20 13:17 UTC, AlexandreBossard commented on protocol.md
> +Then, a second `device_creation` block is created with the *physical device*'s [Device Encryption Key Pair] and [Device Signature Key Pair]. This block is signed with the *virtual device*'s [Device S
We never ever describe it like it. I'm not sure this is a protocol thing or an implementation detail.

2019-11-20 13:19 UTC, AlexandreBossard commented on protocol.md
> +For the *application* to offer Email as a verification method, they need to send `HTTP` requests to the *Tanker server*. To allow that, the *application* administrator needs to register their domain
It's... what I've written ? right ?

2019-11-22 13:12 UTC, tux3 requested changes

2019-11-22 13:12 UTC, tux3 commented on concepts.md
> +[Verification Method]: concepts.md#verification-method "A verification method allows a user to retrieve its verification key"
their

2019-11-22 13:12 UTC, tux3 commented on concepts.md
> +A [Verification Method] is used to protect the encrypted [Verification Key] on the *Tanker server*. The user must provide a proof of their identity to access it. This proof method must be establish b
establish +ed
What do you think of `The *user* must establish this proof with the *application* and the *Tanker server* [...]` ?

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +[Delegation Token]: concepts.md#delegation-token "Part of a Secret Permanent Identity. Combinaison of a ephemeral private key and the user id"
s/a/an/

Combinaison -> translate to english -> Combination

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +[Delegation Token]: concepts.md#delegation-token "Part of a Secret Permanent Identity. Combinaison of a ephemeral private key and the user id"
user id -> user ID

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +[Delegation Token]: concepts.md#delegation-token "Part of a Secret Permanent Identity. Combinaison of a ephemeral private key and the user id"
Also, it's not just a signature key pair (but do mention it!) and a user id, the whole point of it is that the server signs the delegation. So it's a combination of all three.

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +[Verification Method]: concepts.md#Verification-method "A verfication methond allow a user to retrieve its verification key"
Y'all'd've already defined that in concepts.md tho?

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +[Resource ID]: concepts.md#resource-id
Why does this not have a definitIon?

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Before being able to encrypt/decrypt and exchange keys, a *user* must exist on the *Trustchain*. This means they have at least one valid *device* (not revoked) registered on *Trustchain*. To exists o
>will ask *user*'s proof

ask for the *user*'s proof

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Before being able to encrypt/decrypt and exchange keys, a *user* must exist on the *Trustchain*. This means they have at least one valid *device* (not revoked) registered on *Trustchain*. To exists o
authentication from the -> authentication against the

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Before being able to encrypt/decrypt and exchange keys, a *user* must exist on the *Trustchain*. This means they have at least one valid *device* (not revoked) registered on *Trustchain*. To exists o
> generate [Secret Permanent Identity]

generate a

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Before being able to encrypt/decrypt and exchange keys, a *user* must exist on the *Trustchain*. This means they have at least one valid *device* (not revoked) registered on *Trustchain*. To exists o
Extreme competition-level nitpick: there's an extra space before the full stop in `*application server* .`

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Before being able to encrypt/decrypt and exchange keys, a *user* must exist on the *Trustchain*. This means they have at least one valid *device* (not revoked) registered on *Trustchain*. To exists o
`To exists on the *Trustchain*` <- this reads a bit weird, authenticating isn't what makes you exist on the trustchain, it's more that it authorizes registration. How about `To register on the *Trustchain*?`

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +One of the first action taken by *Tanker Core* is to ask the *Tanker server* for the user existence on the *Trustchain* and if so, if the current *device* exists. The result of this request will eith
user existence -> user's existence

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +One of the first action taken by *Tanker Core* is to ask the *Tanker server* for the user existence on the *Trustchain* and if so, if the current *device* exists. The result of this request will eith
>One of the first action taken by *Tanker Core* is to ask the *Tanker server* for the user existence on the *Trustchain* and if so, if the current *device* exists

That's not quite right, the SDK asks for both user and device existence in the same request, so replace the "if so" part by something like `checks with the *Tanker server* that the user and device exist on the *Trustchain*"`

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +First, if they are not found, *Tanker Core* creates a [Device Encryption Key Pair], [Device Signature Key Pair], for the *physical device*, and a [User Encryption Key Pair]. It stores them to the [Lo
stores them to the -> in the

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +A first `device_creation` block is constructed with the *virtual device*'s [Device Encryption Key Pair] and [Device Signature Key Pair] and the encrypted [User Encryption Key Pair]. This block is sig
`ken]fou`

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +A first `device_creation` block is constructed with the *virtual device*'s [Device Encryption Key Pair] and [Device Signature Key Pair] and the encrypted [User Encryption Key Pair]. This block is sig
>constructed with the *virtual device*'s [Device Encryption Key Pair]

We don't build it with the key pairs, just the public keys (same thing below)

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Then, a second `device_creation` block is created with the *physical device*'s [Device Encryption Key Pair] and [Device Signature Key Pair]. *Tanker Core* creates a new ephemeral key pair, signs this
to signs ->  to sign

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Finally, Both `device_creation` *block*s are pushed to the *Trustchain*, the *virtual device* before the *physical one*, and the [Verification Key] is uploaded to the *Tanker server* according to the
Finally, Both -> Consider Un-Titling The Case

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Finally, Both `device_creation` *block*s are pushed to the *Trustchain*, the *virtual device* before the *physical one*, and the [Verification Key] is uploaded to the *Tanker server* according to the
`is uploaded to the server` -> That part is uptional (otherwise we wouldn't have strict bona-fide end-to-end-ness)

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Prerequisite: the *user* used one of its registered verification method to let *Tanker Core* retrieve its [Verification key], see [Verification Methods](#verification-methods) for a complete explanat
`to let *Tanker Core* retrieve its [Verification key]` -> Again, this is opt-in. Users can enjoy the UX of entering their verification key.

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +Given the *user*'s [Verification Key], the steps to register a new *device* are as follows:
Maybe remove the unnecessary "as follows"

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. The *user* uses one the [Verification Method] available to him to obtain its [Verification Key]
Verification Methods  
their verif key

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* requests the last *encrypted user key* from the *Tanker server*
> last *encrypted user key* 
The last user key encrypted for the virtual device

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* extracts the encrypted [User Encryption Key Pair] and the *device id* from it
Maybe merge this step with the above

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* constructs the new *device*'s `device_creation` *block* with the *device id*, retrieved from the *Tanker server*, as the block author
`the *device id*` -> Maybe mention again that this is the virtual device's

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* uses the *virtual device*'s private [Device Signature Key Pair] to signs the delegation and fill the block's *delegation signature* field
This is in the wrong order, it should be before the "construct the device_creation block" step above

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *device* initiate the authentication by requesting for an *authentication challenge* from *Tanker server*. This challenge is an array of bytes made of:
initiates  
requesting for an -> requesting an  
`is an array of bytes made of` -> just `made of` sounds good to me (in fact, it's UTF-8, but we don't need to document those details)

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +- A fixed prefix shared between the *Tanker server* and all of the *Tanker Core* implementations
Maybe mention that the prefix's purpose is to prevent using the client as a signing oracle.

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +*Tanker Core* requires at least one verification method to be registered at all time for the *user*. These methods allow a *user* to register a new *device* on the trustchain by providing a shared pr
`by providing a shared proof between him and the *Tanker server*.` <- I think you can just remove this part, it's already implied by the definition of a verification method (and not strictly true if you use the raw verification key: no server involved here)

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +For this purpose, during [user registration](#user_registration) *Tanker Core* creates a *virtual device* and pushes its `device_creation` block. This *device* is not a "physical" one, it has no [Loc
`The [Verification Key] is encrypted with the [User Secret] and stored on the *Tanker server*.` <- But only sometimes

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +*User*s can use their [Verification Key] 'as is' when registering a new device. But, *Tanker Core* proposes an easier way to handle the [Verification Key].
>. But,

Nit: I think you just need either a comma or a full stop

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *user* provides a passphrase when registering a new [Verification Method]. The passphrase will be hashed by *Tanker Core* before sending it to the *Tanker server*. The *Tanker server* will rehash
`along side` -> That's been one word for the past two millenia =]

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *user* provides a passphrase when registering a new [Verification Method]. The passphrase will be hashed by *Tanker Core* before sending it to the *Tanker server*. The *Tanker server* will rehash
seed -> salt

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *user* provides a passphrase when registering a new [Verification Method]. The passphrase will be hashed by *Tanker Core* before sending it to the *Tanker server*. The *Tanker server* will rehash
`the user [Verification Key]` -> user's

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +When the *user* needs to [register a new device](#device-registration), they will provide their passphrase. *Tanker Core* will hash the passphrase before sending it to the *Tanker server*. Then, the
`*Tanker Core* will hash the passphrase before sending it to the *Tanker server*. Then, the *Tanker server* will rehash with the seed the received hashed passphrase` -> That's copypasted from above, isn't it? I think you can just refer to "hash the passphrase as described above"?

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +When the *user* needs to [register a new device](#device-registration), they will provide their passphrase. *Tanker Core* will hash the passphrase before sending it to the *Tanker server*. Then, the
and matched -> match

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +When the *user* needs to [register a new device](#device-registration), they will provide their passphrase. *Tanker Core* will hash the passphrase before sending it to the *Tanker server*. Then, the
`If the match happened` -> If they match

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +For the *application* to offer Email as a verification method, they need to send `HTTP` requests to the *Tanker server*. To allow that, the *application* administrator needs to register their domain
I think he means "replace the first their by the"

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. The *application* forwards the email of the *user* and the [Verification Code] to *Tanker Core*
> forwards the email of the *user* and the [Verification Code]

The email **address** and the code

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The process to [register a new device](#device-registration) with an email [Verification Method] is the same as described above. The only difference is that at the end of the process the *Tanker serv
>returned

returns

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The process to [register a new device](#device-registration) with an email [Verification Method] is the same as described above. The only difference is that at the end of the process the *Tanker serv
We might want to mention that there's throttling, to prevent blatant brute-force attacks on the verification code.

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *user* authenticates against the OpenID Connect provider, which will allow the *application* to receive the *user* `ID Token`. Then, the *application* can provides this `ID Token` to *Tanker Core
`can provides` -> can provide or provides

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The *user* authenticates against the OpenID Connect provider, which will allow the *application* to receive the *user* `ID Token`. Then, the *application* can provides this `ID Token` to *Tanker Core
>and hash it before storing it

, hash it, and store it.

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +The process to [register a new device](#device-registration) with an `OIDC` [Verification Method] is the same as described above. The only difference is that at the end of the process *Tanker server*
>process *Tanker server*

, the

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* looks for the [Group Encryption Key Pair] associated with [GID](#group-id) in the [Local Encrypted Storage]
>with [GID](#group-id)

![teh](https://cdn.shopify.com/s/files/1/1829/4817/products/qc-teh.jpg?v=1571448906)

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +This operation adds users to an existing user group. The group ID, [Group Encryption Key Pair] and the [Group Signature Key Pair] remains unchanged at the end of the operation.
remains -> remain
Nit: oxford comma

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. The *application* fetches the [Public Permanent Identity] for each *group member* to remove
Merge w/ above

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* fetches all future *group member*s `device_creation` *block*s from the *Trustchain*
s'

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +1. The *application* fetches the [Public Permanent Identity] for each *group member* to add
Not necessarily pernanent identities, could be provisional

2019-11-22 13:12 UTC, tux3 commented on protocol.md
> +- The [Preregistration](#preregistration) section describes how a registred user can shared a resource to a non yet registered user.
uncapitalize teh preregistration

2019-11-22 15:40 UTC, AlexandreBossard commented on protocol.md
> +[Verification Method]: concepts.md#Verification-method "A verfication methond allow a user to retrieve its verification key"
Yes, there is no #includee in .md

2019-11-25 14:08 UTC, AlexandreBossard commented on protocol.md
> +Finally, Both `device_creation` *block*s are pushed to the *Trustchain*, the *virtual device* before the *physical one*, and the [Verification Key] is uploaded to the *Tanker server* according to the
That's the 'according to the...' hints to.

2019-11-25 14:10 UTC, AlexandreBossard commented on protocol.md
> +Prerequisite: the *user* used one of its registered verification method to let *Tanker Core* retrieve its [Verification key], see [Verification Methods](#verification-methods) for a complete explanat
I know, but this is more of an exception that a rule. Also the appointed reference will en light them.

2019-11-25 14:19 UTC, AlexandreBossard commented on protocol.md
> +1. *Tanker Core* extracts the encrypted [User Encryption Key Pair] and the *device id* from it
Your opinion has been cordially discarded.

2019-11-25 14:27 UTC, AlexandreBossard commented on protocol.md
> +1. *Tanker Core* uses the *virtual device*'s private [Device Signature Key Pair] to signs the delegation and fill the block's *delegation signature* field
weird

2019-11-25 14:29 UTC, AlexandreBossard commented on protocol.md
> +- A fixed prefix shared between the *Tanker server* and all of the *Tanker Core* implementations
The should figured that out. Justification should be part of this document... probably.

2019-11-25 14:29 UTC, AlexandreBossard commented on protocol.md
> +- A fixed prefix shared between the *Tanker server* and all of the *Tanker Core* implementations
I am not event sure this should not be considered as an implementation detail.

2019-11-25 14:32 UTC, AlexandreBossard commented on protocol.md
> +*Tanker Core* requires at least one verification method to be registered at all time for the *user*. These methods allow a *user* to register a new *device* on the trustchain by providing a shared pr
This is the definition of the verification method. So I am not sure what's wrong here..

2019-11-25 14:35 UTC, AlexandreBossard commented on protocol.md
> +When the *user* needs to [register a new device](#device-registration), they will provide their passphrase. *Tanker Core* will hash the passphrase before sending it to the *Tanker server*. Then, the
This kind of repetition doesn't bother me much in this kind of doc. I prefer to be boringly explicit.

2019-11-25 14:38 UTC, AlexandreBossard commented on protocol.md
> +The process to [register a new device](#device-registration) with an email [Verification Method] is the same as described above. The only difference is that at the end of the process the *Tanker serv
This is implementation, I think.

2019-11-25 14:40 UTC, AlexandreBossard commented on protocol.md
> +The *user* authenticates against the OpenID Connect provider, which will allow the *application* to receive the *user* `ID Token`. Then, the *application* can provides this `ID Token` to *Tanker Core
meh ?

2019-11-25 14:44 UTC, AlexandreBossard commented on protocol.md
> +- The [Preregistration](#preregistration) section describes how a registred user can shared a resource to a non yet registered user.
Why, it's a title ?

2019-11-25 15:11 UTC, tux3 commented on protocol.md
> +1. *Tanker Core* extracts the encrypted [User Encryption Key Pair] and the *device id* from it
:ok_hand:

2019-11-25 15:13 UTC, tux3 commented on protocol.md
> +- The [Preregistration](#preregistration) section describes how a registred user can shared a resource to a non yet registered user.
Consistency!

2019-11-26 09:28 UTC, tux3 approved these changes
Overall, LGTM

2019-11-26 13:16 UTC, merged